### ISSUE TITLE
evo mbed lib name mismatch

### ISSUE THREAD

**Issue by marcomasa** [evocortex/evo_rd_platform#2]
When installing the debian package, the library installs as
"evo-mbed-tools"
but the ROS package requires it to be named
"evo_mbed_tools"

**Comment by feesmrt** [comment]
You have to take care:
If you update the two repositories with the open pull-requests you cannot build the packages because:
evo_rd_platform_exampled
evo_robot_base_interface 
are both pulled from the NOT MERGED MASTER. This means there is the old link to evo_mbed_tools which is not a valid naming for debian packages.
If you want to test your build before merge run 'wstool update' in your evo_rd_platform and then checkout the devel branches in the both repositories.

This bug will be gone after the pull request is completed.

**Comment by feesmrt** [comment]
Fixed after merge of evo_rd_platform_examples and evo_robot_base_interface
